const t={
es:{eyebrow:'MARTROLAB · SOLUCIONES DIGITALES',navSolutions:'Soluciones',navProjects:'Proyectos',navAbout:'Nosotros',navContact:'Contacto',quote:'Solicitar cotización',heroTitle:'Tecnología diseñada para <em>impulsar negocios.</em>',heroText:'Desarrollamos soluciones digitales que integran estrategia, diseño y tecnología para fortalecer operaciones, optimizar procesos y crear nuevas oportunidades de crecimiento.',discover:'Conoce nuestras soluciones',explore:'Explora nuestros proyectos →',cap1:'DESARROLLO DIGITAL',cap2:'APLICACIONES',cap3:'SISTEMAS',cap4:'SOLUCIONES A MEDIDA',solutionsTitle:'Soluciones digitales con visión de negocio',solutionsIntro:'Desarrollamos tecnología alineada con los objetivos de cada organización. Creamos soluciones funcionales, escalables y adaptadas a las necesidades de cada proyecto.',s1:'Presencia digital',s1p:'Experiencias digitales que fortalecen la identidad, comunicación y presencia comercial de cada negocio.',s2:'Aplicaciones y plataformas',s2p:'Soluciones funcionales e intuitivas diseñadas alrededor de necesidades concretas.',s3:'Sistemas empresariales',s3p:'Herramientas para optimizar procesos, centralizar información y mejorar la gestión operativa.',s4:'Soluciones a medida',s4p:'Desarrollo tecnológico específico para requerimientos, procesos y objetivos particulares.',projectsTitle:'Proyectos que demuestran resultados',projectsIntro:'Nuestro portafolio está integrado por soluciones reales. Explora cada caso para conocer el enfoque, los beneficios y el resultado.',filterAll:'Todos',filterRestaurants:'Restaurantes',filterSchools:'Colegios/Escuelas',digitalMenu:'Menú digital',locosTag:'RESTAURANTES',locosShort:'Experiencia digital diseñada para facilitar la consulta del menú y acercar al cliente al pedido desde dispositivos móviles.',caseArrow:'Ver caso de estudio →',aboutTitle:'Tecnología orientada a resultados.',aboutText:'MARTROLAB desarrolla soluciones digitales adaptadas a las necesidades de cada proyecto, integrando diseño, funcionalidad y tecnología con una visión orientada al negocio.',quoteTitle:'Conversemos sobre tu proyecto',quoteIntro:'Cuéntanos qué necesitas. Analizaremos tu proyecto para preparar una propuesta acorde con sus objetivos y alcance.',name:'Nombre',business:'Empresa o negocio',sector:'Tipo de negocio',need:'¿Qué solución necesitas?',optWeb:'Sitio web',optApp:'Aplicación',optSystem:'Sistema para mi negocio',optCustom:'Solución personalizada',optUnsure:'No estoy seguro',description:'Descripción del proyecto',privacy:'He leído y acepto el Aviso de Privacidad.',send:'Solicitar cotización',direct:'¿Prefieres contacto directo?',directText:'También podrás conversar con MARTROLAB por WhatsApp Business.',whatsappSoon:'WhatsApp · Próximamente',cta:'Construyamos la solución que tu negocio necesita.',start:'Iniciar un proyecto',privacyLink:'Aviso de Privacidad'},
en:{eyebrow:'MARTROLAB · DIGITAL SOLUTIONS',navSolutions:'Solutions',navProjects:'Projects',navAbout:'About',navContact:'Contact',quote:'Request a quote',heroTitle:'Technology designed to <em>move businesses forward.</em>',heroText:'We create digital solutions that combine strategy, design, and technology to improve operations, streamline processes, and unlock new opportunities for growth.',discover:'Explore our solutions',explore:'Explore our projects →',cap1:'DIGITAL DEVELOPMENT',cap2:'APPLICATIONS',cap3:'BUSINESS SYSTEMS',cap4:'CUSTOM SOLUTIONS',solutionsTitle:'Digital solutions built around business goals',solutionsIntro:'We build technology around each organization’s goals, creating practical, scalable solutions tailored to the needs of every project.',s1:'Digital presence',s1p:'Digital experiences that strengthen brand identity, communication, and customer-facing presence.',s2:'Applications & platforms',s2p:'Intuitive, functional solutions built around specific business needs.',s3:'Business systems',s3p:'Tools that streamline processes, centralize information, and improve day-to-day operations.',s4:'Custom solutions',s4p:'Purpose-built technology for unique requirements, workflows, and business objectives.',projectsTitle:'Real projects. Practical results.',projectsIntro:'Our portfolio features real solutions built for real businesses. Explore each case to see the challenge, our approach, and the value delivered.',filterAll:'All',filterRestaurants:'Restaurants',filterSchools:'Schools',digitalMenu:'Digital menu',locosTag:'RESTAURANTS',locosShort:'A streamlined digital experience that makes it easier for customers to explore the menu on mobile and move from browsing to ordering.',caseArrow:'View case study →',aboutTitle:'Technology focused on results.',aboutText:'MARTROLAB creates digital solutions tailored to each project, combining design, functionality, and technology with a clear focus on business value.',quoteTitle:'Let’s talk about your project',quoteIntro:'Tell us what you need. We’ll review your project and prepare a proposal based on its goals and scope.',name:'Name',business:'Company or business',sector:'Business type',need:'What do you need?',optWeb:'Website',optApp:'Application',optSystem:'Business system',optCustom:'Custom solution',optUnsure:'I’m not sure yet',description:'Project description',privacy:'I have read and accept the Privacy Notice.',send:'Request a quote',direct:'Prefer to talk directly?',directText:'You’ll also be able to reach MARTROLAB through WhatsApp Business.',whatsappSoon:'WhatsApp · Coming soon',cta:'Let’s build the solution your business needs.',start:'Start a project',privacyLink:'Privacy Notice'}};
let lang=localStorage.getItem('martrolab-lang')||'es';const btn=document.querySelector('#lang');
function setLang(l){lang=l;localStorage.setItem('martrolab-lang',l);document.documentElement.lang=l;document.querySelectorAll('[data-i18n]').forEach(el=>{const v=t[l][el.dataset.i18n];if(v!==undefined)el.innerHTML=v});if(btn)btn.textContent=l==='es'?'EN':'ES';document.title=l==='es'?'MARTROLAB | Soluciones Digitales':'MARTROLAB | Digital Solutions'}
if(btn)btn.onclick=()=>setLang(lang==='es'?'en':'es');setLang(lang);
document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.querySelector('nav').classList.remove('open'));
document.querySelectorAll('.filters button').forEach(button=>{
  button.addEventListener('click',()=>{
    document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));
    button.classList.add('active');

    const filter = button.getAttribute('data-filter') || 'all';

    document.querySelectorAll('.project-card').forEach(card=>{
      const category = (card.getAttribute('data-category') || '').trim().toLowerCase();
      const show = filter === 'all' || category === filter;
      card.hidden = !show;
    });
  });
});
document.querySelector('#quoteForm')?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('#formMsg').textContent=lang==='es'?'Formulario preparado. Lo conectaremos al backend de Cloudflare al publicar MARTROLAB.':'Form ready. We’ll connect it to the Cloudflare backend when MARTROLAB is published.'});
